cmake_minimum_required(VERSION 3.21.0)
project("Chocolate Quake" VERSION 1.1.1 LANGUAGES C)
set(CMAKE_C_STANDARD 99)

set(PACKAGE_NAME ${PROJECT_NAME})
set(PACKAGE_TARNAME "chocolate-quake")
set(PACKAGE_VERSION ${PROJECT_VERSION})
set(PACKAGE_STRING "${PROJECT_NAME} ${PROJECT_VERSION}")
set(PACKAGE_COPYRIGHT "Copyright (C) 1996-2025")
set(PACKAGE_LICENSE "GNU General Public License, version 3")
set(APPSTREAM_APP_ID "io.github.henrique194.chocolate-quake")

# Find math library
find_library(MATH m)
if(MATH)
    link_libraries(${MATH})
endif()

find_package(SDL2 2.26.5 REQUIRED)
if(UNIX AND NOT APPLE)
	find_library(VORBIS_LIBRARY vorbis REQUIRED)
	find_library(VORBISFILE_LIBRARY vorbisfile REQUIRED)
else()
	find_package(Vorbis CONFIG REQUIRED)
endif()

configure_file(config.h.in config.h)

add_subdirectory("src")

if (UNIX AND NOT APPLE)
	install(FILES ${CMAKE_BINARY_DIR}/src/chocolate-quake
		DESTINATION $CMAKE_INSTALL_PREFIX/bin/
		PERMISSIONS WORLD_READ GROUP_READ GROUP_EXECUTE OWNER_READ OWNER_WRITE)
	install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/dist/linux/${APPSTREAM_APP_ID}.svg
		DESTINATION ${CMAKE_INSTALL_PREFIX}/share/icons/hicolor/scalable/apps/
		PERMISSIONS WORLD_READ GROUP_READ OWNER_READ OWNER_WRITE)
	install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/dist/linux/${APPSTREAM_APP_ID}.desktop
		DESTINATION ${CMAKE_INSTALL_PREFIX}/share/applications/
		PERMISSIONS WORLD_READ GROUP_READ OWNER_READ OWNER_WRITE)
	install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/dist/linux/${APPSTREAM_APP_ID}.metainfo.xml
		DESTINATION ${CMAKE_INSTALL_PREFIX}/share/metainfo/
		PERMISSIONS WORLD_READ GROUP_READ OWNER_READ OWNER_WRITE)
endif()
